# Basic Logging Configuration
version: 1
disable_existing_logger: False

# Default Formatting Settings for all Logs
# -- Added request_id to track id across microservices
formatters:
  
  standard: 
    format: "%(asctime)s: %(levelname)s: %(name)s: %(funcName)s: %(message)s"
  
  contextual_formatter: 
    format: "%(asctime)s: %(levelname)s: %(name)s: %(funcName)s: %(report_id)s: %(message)s"


# Default Filtering Settings
filters:
  
  context_filter: 
    (): Logging.Filters.ContextFilter


# Default Handler Settings
handlers:
  
  context_handler:
    level: DEBUG
    formatter: contextual_formatter
    class: logging.StreamHandler
    stream: ext://sys.stdout
    filters: [ context_filter,  ]

  console:
    level: DEBUG
    formatter: standard
    class: logging.StreamHandler
    stream: ext://sys.stdout

# Specific logger settings
loggers:
  
  Routes :
    level: DEBUG
    handlers: [ context_handler ]
    propagate: False

  Authentication.Authentication:
    level: DEBUG
    handlers: [ context_handler ]
    propagate: False

  TaskHandler.TaskHandler:
    level: DEBUG
    handlers: [ context_handler ]
    propagate: False

  Utility.Utility:
    level: DEBUG
    handlers: [ console ]
    propagate: False

# Root Settings
root:
  
  level: DEBUG
  handlers: [ console ]
  propagate: False