# Basic Logging Configuration
version: 1
disable_existing_logger: true

# Default Formatting Settings for all Logs
# -- Added request_id to track id across microservices
formatters:
  standard: 
    format: "%(asctime)s: [%(levelname)s]: %(report_id): %(name)s: %(message)s"

# Default Handler Settings
handlers:
  default:
    level: DEBUG
    formatter: standard
    class: logging.StreamHandler
    stream: ext://sys.stdout

# Filter Settings
filters:
  context_filter:
    class: Logging.Filters.ContextFilter

# Specific logger settings
loggers:
  root:
    handlers: default
    formatter: standard
    propogate: false
    level: DEBUG