# Basic Logging Configuration
version: 1
disable_existing_logger: true

# Default Formatting Settings for all Logs
# -- Added request_id to track id across microservices
formatters:
  standard: 
    format: "%(asctime)s: [%(levelname)s]: %(name)s: %(message)s"
  contextual_formatter: 
    format: "%(asctime)s: [%(levelname)s]: %(report_id)s: %(name)s: %(message)s"

# Default Handler Settings
handlers:
  console:
    level: INFO
    formatter: standard
    class: logging.StreamHandler
    stream: ext://sys.stdout

# Filter Settings
filters:
  context_filter:
    class: Logging.Filters.ContextFilter

# Specific logger settings
root:
  level: INFO
  handlers: [console]
